import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_Components/Navbar/page";
import Footer from "./_Components/Footer/page";
import { Toaster } from "_/components/ui/sonner";
import MySessionProvider from "./_Components/MySessionProvider/MySessionProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <MySessionProvider>
          <Navbar />

          {/* main content */}
          <main className="flex-grow pt-14 min-h-screen">
            {children}
          </main>

          <Toaster />
          <Footer />
        </MySessionProvider>
      </body>
    </html>

  );
}
